//
//  UserDefaultsKeys.h
//  SniffNetBar
//

#import <Foundation/Foundation.h>

typedef NSString * SNBUserDefaultsKey NS_TYPED_ENUM;

FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySelectedNetworkDevice;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyMapProvider;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyMapProviderURLTemplate;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyMapProviderLatKey;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyMapProviderLonKey;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyThreatIntelEnabled;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyAssetMonitorEnabled;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyDailyStatisticsEnabled;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyKnownNetworkDevices;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyShowTopHosts;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyShowTopConnections;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyShowMap;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeyShowProcessActivity;

// Section collapse/expand states
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionThreatsExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionNetworkActivityExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionNetworkDevicesExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionTopHostsExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionTopConnectionsExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionNetworkAssetsExpanded;
FOUNDATION_EXPORT SNBUserDefaultsKey const SNBUserDefaultsKeySectionProcessActivityExpanded;
